name: Lint
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
          scandir: .
          format: gcc
          version: stable
      - name: Black formatting (Python)
        uses: psf/black@stable
        with:
          options: --check --verbose
          src: .
