name: Black (Python)
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Black formatting for Python scripts
        uses: psf/black@stable
        with:
          options: --check --verbose
          src: .
